#!/usr/bin/env bash


for filename in plain_policies/*.txt; do
    echo '''

##################################
#             POLICY             #
##################################

    '''
    echo "-> $filename opened"
    less "$filename"
    read -n 1 -p "actions: y (select), n (drop), e (exit) " yne

    case $yne in

    y)
        echo "-> $filename select"
        mv $filename manually_selected
        ;;

    n)
        echo "-> $filename drop"
        mv $filename manually_dropped
        ;;

    *)
        exit
        ;;
    esac
done
